### ISSUE TITLE
Binary converter 

### ISSUE THREAD

**Issue by ghost** [thegeekyb0y/pythonprojects#2]
#function to convert decimal to binary.
def binary(num):
    if num == 0:
        return 0
    else :
        res = num % 2 + 10 * binary (num // 2)
        return res
deci = int(input('Enter a Decimal Number : '))

#function to convert binary to decimal.    
def decimal(num):
    sq = 0
    res = 0
    rev_num = num[::-1]
    for digit in rev_num :
        res += int(digit) * 2**sq
        sq += 1
    return res
binry = input('Enter a Binary digit : ')

print(f'\nBinary number of {deci} is : {decimal(binry)}')

print(f'\nDecimal number of {binry} is : {binary(deci)}')

**Comment by thegeekyb0y** [comment]
Thankyou
